server:
  port: 8081

spring:
  data:
    redis:
      host: localhost # root
      port: 6379
      password:

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

async:
  executor: prod